### ISSUE TITLE
parameter setting issue in immunedeconv 

### ISSUE THREAD

**Issue by amanzju** [grst/immunedeconv#16]
Hi Gregor,
Thanks a lot for developed a wonderful integrated package. I am so much interested to use this package. I am  using this package on windows due to lack of proper experience about server computer. I am wondering about a question, 

is it possible to set user defined same cell types and same signature for all methods? 

I have looked some websites but did not get proper guide line. I will be grateful to you if kindly give me some instruction. 

Aman

**Comment by grst** [comment]
Hi Aman, 

it is currently not possible to transfer signatures between the methods. 
This is due to the conceptual differences between methods (marker genes vs. deconvolution; feature selection on signature matrices, ...)

This is currently discussed here:
https://github.com/grst/immunedeconv/issues/15

Cheers, 
Gregor

**Comment by amanzju** [comment]
Hello Gregor,

Thanks a lot for your quick reply and for the explanation of my question.

Aman
